CC TESTE
   CD A:4 ; variavel v1
   CD B:4 ; variavel v2
   MREF NEW
   MREF SOMA
ENDC TESTE

MC TESTE.NEW
   MOV 20, SELF.A ; A := 20
   MOV 10, SELF.B ; B := 10
   RET

MC TESTE.SOMA
   ADD SELF.A:SELF.B ; ADD THE VALUE '20' WITH '10'
   RET

PROGRAM START
   COI  I1:TESTE.NEW ;CREATE A OBJECT INSTANCE
   CALL I1.SOMA      ;CALL 'SOMA' METHOD FROM OBJECT INSTANCE 
   RET
